---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=4600
  sudo: yes

- name: 'add php7 repository'
  raw: 'sudo add-apt-repository ppa:ondrej/php -y'

- name: 'update ubuntu libraries'
  raw: 'sudo apt update -y'

- name: Install required software
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - mysql-server
    - php7.0-mysql
    - php7.0
    - libapache2-mod-php7.0
    - python-mysqldb
    - php7.0-cli
    - php7.0-cgi
    - php7.0-gd


- name: 'install python'
  raw: 'sudo apt-get -y install python'

- name: 'install python'
  raw: 'sudo apt-get -y install python-pip'

- name: 'install python'
  raw: 'sudo apt-get -y install python3-pip'

- name: Make sure pymysql is present
  become: true 
  pip:
    name: pymysql
    state: present

